### ISSUE TITLE
Duplicate files and functions are confusing

### ISSUE THREAD

**Issue by jforaker** [supnate/rekit-example#1]
You have 2 files with the same content:
`src/features/topic/constants.js`
and
`src/features/topic/redux/constants.js` 

More info: https://github.com/supnate/rekit-example/search?utf8=%E2%9C%93&q=export+const+SAVE_TOPIC_BEGIN+&type=Code

You also have the same function in multiple places:
https://github.com/supnate/rekit-example/blob/3cd8168d846f165553ecb0716c1b4d36709c38bc/src/features/topic/redux/saveTopic.js#L9
and 
https://github.com/supnate/rekit-example/blob/3cd8168d846f165553ecb0716c1b4d36709c38bc/src/features/topic/actions.js#L18

This is a little confusing to have in the example/demo. I like this project and would love to see this bit cleared up.

**Comment by supnate** [comment]
Yes it's really confusing. I forgot to remove the old code after migrating to the new folder structure. Now it's cleared. Thank you very much for reporting this!

**Comment by jforaker** [comment]
Thanks!
