### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by getmonyinfo** [supnate/rekit-example#2]
![qq 20161024105012](https://cloud.githubusercontent.com/assets/2359621/19632291/b2ab1024-99d7-11e6-8718-f955d348ecc3.png)

**Comment by supnate** [comment]
Thanks for reporting. It's now fixed.

**Comment by getmonyinfo** [comment]
Hello, there is still errors
![image](https://cloud.githubusercontent.com/assets/2359621/19643824/f2dd1948-9a1e-11e6-8a1b-e3c4b902bc1e.png)

**Comment by supnate** [comment]
You need to access http://localhost:6076/rekit-example

**Comment by getmonyinfo** [comment]
gotta , thanks, i love this tool

**Comment by supnate** [comment]
Glad to know it. Thank you!
