### ISSUE TITLE
Handle cross-topic actions here 可否具体说说

### ISSUE THREAD

**Issue by summitxf** [supnate/rekit-example#3]
很喜欢你的这种层级划分，但是Handle cross-topic actions here 这块可不可以具体说说呢，还是有些不理解，谢谢

```
export default function reducer(state = initialState, action) {
  let newState;
  switch (action.type) {
    // Handle cross-topic actions here
    default:
      newState = state;
      break;
  }
  return reducers.reduce((s, r) => r(s, action), newState);
}
```

**Comment by supnate** [comment]
首先，你要了解 Rekit 的 action/reducer 和官方标准方式的区别：Rekit 中一个 action 文件中同时包含 action 和对应的 reducer，可以参考：http://rekit.js.org/docs/one-action-one-file.html
或者：https://segmentfault.com/a/1190000007265799

理解了这种方式后你会发现如果一个 reducer 不对应 action，或者对应多个 action 时，没有合适的地方写对应的代码，所以 reducer.js 就是设计为写这些 reducer 的。这里是一个实际使用的例子，可能有点复杂，但是应该可以帮助理解：
https://github.com/supnate/command-pad/blob/master/src/features/home/redux/reducer.js

**Comment by summitxf** [comment]
可否理解为这里的CMD_FINISHED&CMD_OUTPUT 是更新多个其它Action需要用到的state
就是说某个action操作的state，not only self state but also public shared state?

比如某个添加成功操作action，去更新公共组件 个数统计count的值。

**Comment by supnate** [comment]
> 比如某个添加成功操作action，去更新公共组件 个数统计count的值。

没错，就是这样的。
